### ISSUE TITLE
Upload files to graphical interface

### ISSUE THREAD

**Issue by gititub** [Thomas-Rowlands/GWAS-Miner#2]
The interface seems to work fine but it doesn't recognize any file. What kind of files are allowed?

**Comment by Thomas-Rowlands** [comment]
Hi,

Apologies, I'll get the readme updated with this info.


This project is designed to work with BioC documents, with Auto-CORPus used to generate article BioC and Table-BioC JSON files (https://github.com/omicsNLP/Auto-CORPus).

Thanks,

-Thomas

**Comment by gititub** [comment]
Many thanks! 😊Have a nice day! AmeliaEl dia 3 de maig 2023 9:17, Thomas Rowlands ***@***.***> va escriure:
Hi,
Apologies, I'll get the readme updated with this info.
This project is designed to work with BioC documents, with Auto-CORPus used to generate article BioC and Table-BioC JSON files (https://github.com/omicsNLP/Auto-CORPus).
Thanks,
-Thomas
